### PR TITLE
added operator mono support

### PR DESCRIPTION
**Pull request by ghost**
screen shot 2018-02-05 at 11 38 50

### CODE REVIEW

**Comment by ghost** [comment]
@thomaspink , you might want to make this a theme option eg: 'github - operator'.

**Comment by thomaspink** [comment]
@BrianDGLS thanks for the pull request
As i don't want font specific stuff in the base theme we could add it into a subtheme (github-operator). Or what do you mean behind an option?

**Comment by ghost** [comment]
@thomaspink  Morning, 
I agree it shouldn't be in the base theme.

What I meant by an option is similar to how other themes eg: [Palenight](https://github.com/whizkydee/vscode-material-palenight-theme), handle variants.

screen shot 2018-02-07 at 09 21 22

**Comment by thomaspink** [comment]
@BrianDGLS sorry for the long delay. 
I looked into palenight and they are providing a dedicated theme for operator support:
https://github.com/whizkydee/vscode-material-palenight-theme/blob/master/themes/palenight-operator.json

I think we could do the same. Can you change the PR so that you create a github-operator.json in the themes folder and put the operator stuff there?

**Pull request closed without merging**
