### PR TITLE
Add tab background, and border

### PR DESCRIPTION
**Pull request by ogustavo-pereira**
Add color of github in tab and border

### CODE REVIEW

**Comment by thomaspink** [comment]
@oguhpereira Thank you for you pull request.

But i cannot see why the borders and tabs should be blue? Do you have a reference for this?

screen shot 2018-01-18 at 09 27 21

**Comment by oguhpereira** [comment]
Hi thomas I get the reference of GitHub desktop colors. I set border blue for remember the color of GitHub but it don't have border blue in GitHub.

Thanks!
________________________________

**Comment by thomaspink** [comment]
@oguhpereira can you attach a reference link or image where this design is shown?

**Comment by oguhpereira** [comment]
capturar

**Comment by thomaspink** [comment]
Thank you @oguhpereira . i will take a look into this and make suggestions to you pull request

**Pull request closed without merging**
